// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class hackingscoresmodelforMVPlasttime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hackingscoresmodelforMVPlasttime));
        
        string IMigrationMetadata.Id
        {
            get { return "201611170431375_hacking scores model for MVP last time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
